# Generated by Django 4.1.3 on 2022-12-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=100)),
                ('anio_nacimiento', models.CharField(default='DEFAULT VALUE', max_length=20)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
